### ISSUE TITLE
Add the option to hide steps with display none instead of removing them from the DOM

### ISSUE THREAD

**Issue by gkpo** [alan2207/react-multistep-wizard#11]
I'm using the wizard with react-hook-form which uses refs, as a way to access the form content.
My issue is that the refs from the first steps don't exist anymore when I arrive on the last step. So my form fields are considered empty... :/
I think that if they weren't removed from the DOM, but just hidden, it would solve my issue.

**Comment by alan2207** [comment]
Hi @gkpo , I have made a codesandbox example in order to make it work together:
https://codesandbox.io/s/unruffled-glitter-cuxnq?file=/src/App.tsx

The other aproach is to collect all the values from multiple forms in a lifted state as explained here:
https://react-hook-form.com/advanced-usage#WizardFormFunnel

Cheers!

**Comment by gkpo** [comment]
Thanks for your reply, that solution works indeed 👍
